version: '2'
services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_DATABASE: dbms-cohort-starport_development
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbms_starport_db_dev:/var/lib/mysql
      - ./db/dev.my.cnf:/etc/mysql/conf.d/dev.my.cnf
    ports:
      - "3307:3306"

  web:
    build: .
    links:
      - db
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3000"
      - "8081:8080"
    volumes:
      - .:/usr/src/app
    volumes_from:
      - gems

  gems:
    image: busybox
    volumes:
      - /ruby_gems

  redis:
    image: redis:latest

volumes:
  dbms_starport_db_dev:
